name: Auto Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run commands on Ubuntu server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/myproject
            git pull origin main
            npm run build
            # Buraya build lazımdırsa əlavə et:
            # npm install
            # python manage.py migrate
            # systemctl restart nginx
            # pm2 restart app
